name: Publish

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[A-Za-z0-9]+-service-[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get service name and version
        id: service
        run: |
          echo "service=$(echo ${{ github.ref }} | cut -d '/' -f 3 | cut -d '-' -f 1-2)" >> $GITHUB_OUTPUT
          echo "version=$(echo ${{ github.ref }} | cut -d '/' -f 3 | cut -d '-' -f 3)" >> $GITHUB_OUTPUT

      - name: Print service and version
        run: |
          echo ${{ steps.service.outputs.service }}
          echo ${{ steps.service.outputs.version }}

        # Setup Docker
        # Docker Build
        # Build based on service and version
        # Dockerhub Login
        # Docker push

        